---
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Build docker image
          command: docker-compose build app
      - run:
          name: Install composer dependencies
          command: bin/composer install --no-dev
      - run:
          name: Start docker-compose containers
          command: docker-compose up -d
      - run:
          name: Wait for containers to ready
          command: for i in `seq 1 10`; do docker-compose exec app true && exit 0; echo "Waiting for docker ready..."; sleep 2; done; exit 1
      - run:
          name: Wait for database to ready
          command: docker-compose exec app docker/wait_for_db
      - run:
          name: Make uploads writeable
          command: mkdir -p ./uploads && docker-compose exec app chmod 777 ./uploads
      - run:
          name: Make archive writeable
          command: docker-compose exec app chmod 777 ./archive
      - run:
          name: Test with bats
          command: docker-compose exec app bats -r tests/

workflows:
  version: 2
  commit:
    jobs:
      - build
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
